on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}

          - name: Install dependencies
            run: npm install

          - name: Lint source
            run: npm run lint

          - name: Build source
            run: npm run build

          - name: Test source
            run: npm run test
